image:
  repository: linuxserver/heimdall
  tag: 2.5.8@sha256:481920a4653faae7ef93b04be434ed98108db9df627a2c503834368e8c2f577c
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            startup:
              enabled: true
