---
version: "3"

dotenv: [".env"]

includes:
  git:
    taskfile: .taskfiles/git.tasks.yml
    internal: true

  helm:
    taskfile: .taskfiles/helm.tasks.yml
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  backup:pvs:
    desc: Backup Persistent Volumes
    cmds:
      - ./scripts/backup_pvs.sh
    env:
      BACKUP_PV_DIR: "{{.ROOT_DIR}}/persistentvolumes"

  deploy:
    desc: Deploy cluster from scratch
    cmds:
      - task: deploy:csi
      - task: deploy:pvs
      - task: deploy:pvcs

  deploy:csi:
    desc: Deploy CSI
    cmds:
      - task: helm:install
        vars:
          CHART_DIR: "{{.ROOT_DIR}}/addons/democratic-csi"
          CHART_NAME: 'democratic-nfs-client'
          CHART_REPO: 'democratic-csi/democratic-csi'
          CHART_VERSION: '0.14.6'
          NAMESPACE: 'democratic-csi'
          VALUES_YAML: 'nfs-values.yaml'
  
  deploy:pvs:
    desc: Deploy Persistent Volumes
    cmds:
      - kubectl apply -f .
    dir: "{{.ROOT_DIR}}/persistentvolumes"

  deploy:pvcs:
    desc: Deploy Persistent Volume Claims
    cmds:
      - kubectl apply -f .
    dir: "{{.ROOT_DIR}}/persistentvolumeclaims"

  lint:
    desc: Check the syntax on scripts
    cmds:
      - shellcheck "{{.ROOT_DIR}}/scripts/*.sh"

  setup:
    desc: Configure repository for use
    cmds:
      - "{{.ROOT_DIR}}/scripts/configure_templates.sh"
      - "{{.ROOT_DIR}}/scripts/install_velero.sh"
    env:
      ROOT_DIR: "{{.ROOT_DIR}}"

  update:
    desc: "Update repo"
    cmds:
      - task: git:pull
      - task: git:submodule:update