---
version: "3"

dotenv: [".env"]

env:
  NFS_CLUSTER_EXPORT:
  NFS_HOST:
  NFS_INSTANCE_GUID:

includes:

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: "Configure repository for use"
    cmds:
      - ${ROOT_DIR}/scripts/configure_templates.sh
      vars:
        ROOT_DIR: ${ROOT_DIR}
