---
version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task -l
    silent: true

  lint:
    desc: Check the syntax on scripts
    cmds:
      - shellcheck "{{.ROOT_DIR}}/scripts/*.sh"

  setup:
    desc: Configure repository for use
    cmds:
      - "{{.ROOT_DIR}}/scripts/configure_templates.sh"
    env:
      ROOT_DIR: "{{.ROOT_DIR}}"
