apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-pvc
spec:
  storageClassName: synology-smb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
