apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zandronum-server-pvc
spec:
  storageClassName: synology-iscsi-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
