apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f heimdall.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: heimdall
