apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f heimdall.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heimdall
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f heimdall.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/applications-default: "true"
        io.kompose.service: heimdall
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/heimdall:latest
          name: heimdall
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: heimdall-claim0
      restartPolicy: Always
      volumes:
        - name: heimdall-pvc
          persistentVolumeClaim:
            claimName: heimdall-pvc
